#!/bin/bash -e

ARGS=()
ARGS[0]="$1"; shift

MAIN="$(mktemp -d -t nnd)"
trap 'rm -r "$MAIN"' EXIT

SELF="$(cd "$(dirname $0)"; pwd -P)"

mkdir -p "$MAIN/src/nnd"
mkdir -p "$MAIN/src/handlers"

(
  echo 'package main'
  if [ "$#" -ne 0 ]; then
    echo 'import "handlers"'
  fi
  echo 'import "nnd/context"'
  echo 'import "nnd/event"'
  echo 'import "nnd/start"'
  echo 'func main() {'
  echo '  funcs := []func(*context.Context, *event.Event) error{'
  for handler_file in "$@"; do
    cp "$handler_file" "$MAIN/src/handlers"
    for handler in $(cat "$handler_file" | perl -ne 'print "$1\n" if /func\s+([A-Z][A-Za-z0-9_]*?Handler)/'); do
      echo "    handlers.$handler,"
    done
  done
  echo '  }'
  echo '  start.Start(funcs)'
  echo '}'
) > "$MAIN/src/nnd/main.go"

export GOPATH="$MAIN:$SELF"
go install nnd

exec "$MAIN/bin/nnd" $ARGS
