#!/usr/bin/env python
import time
import subprocess

def main():
    print('ok')

subprocess.run(['dropdb', '-U', 'postgres', '--if-exists', '99_e2e_test']);
subprocess.run(['createdb', '-U', 'postgres', '99_e2e_test']);
server = subprocess.Popen(['sh', '-c', '''
    cd server && \
    export PYTHONPATH=. && \
    exec bin/99d ../handlers/{index,stats}.py
'''])
try:
    time.sleep(1)
    main()
finally:
    server.kill()
