#!/usr/bin/env ruby

class Expect
  attr_reader :ok

  def initialize(pid)
    @pid = pid
    @ok = true
  end

  def running
    @ok &&= Process.waitpid(@pid, Process::WNOHANG) == nil
    ok
  end

  def not_running
    @ok &&= Process.waitpid(@pid, Process::WNOHANG) == @pid && $?.exitstatus != 0
    ok
  end
end

def with_server(port, handlers)
  pid = fork { exec("server/nnd 0.0.0.0:#{port} #{handlers.join(' ')}") }
  begin
    sleep 5
    expect = Expect.new(pid)
    yield expect
    raise "test failed" unless expect.ok
  ensure
    begin
      Process.kill('KILL', pid)
      Process.wait(pid)
    rescue Errno::ESRCH
    end
  end
end

def fixture(name)
  "#{File.dirname(__FILE__)}/fixtures/#{name}"
end

def test(file)
  require(file)
end

test './server/test/bad_handler'
test './server/test/bind_privileged_port'
test './server/test/no_handlers'
