#!/bin/bash

TEST_DASHBOARD=1
TEST_SERVER=1

while [ $# -gt 0 ]; do
  case "$1" in
    --skip-dashboard) TEST_DASHBOARD=0;;
    --skip-server)    TEST_SERVER=0;;
  esac
  shift
done

if [ $TEST_DASHBOARD -eq 1 ]; then
  (
    cd dashboard && \
    pulp test
  )
fi

if [ $TEST_SERVER -eq 1 ]; then
  (
    cd server && \
    python3 -m unittest nn.funnel nn.index nn.stats
  )
fi
